version = 0.1

[default]
[default.global.parameters]
stack_name = "autospotter-web"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"  # Required for CloudFront certificates
parameter_overrides = "Environment=dev"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Production environment configuration
[prod]
[prod.deploy.parameters]
stack_name = "autospotter-web-prod"
parameter_overrides = "Environment=prod"
confirm_changeset = false

# Staging environment configuration
[staging]
[staging.deploy.parameters]
stack_name = "autospotter-web-staging"
parameter_overrides = "Environment=staging"
confirm_changeset = false